const express = require("express")
 
const adminRouter = require("./admin.routes")
const userRouter = require("./user.routes")
const bookRouter = require("./book.routes")
const cartoonRouter = require("./cartoon.routes")
const movieRouter = require("./movie.routes")
const subjectRouter = require("./subject.routes")
const resultRouter = require("./result.routes")
const blogRouter = require("./blog.routes")
const riverRouter = require("./river.routes")
const moblieRouter = require("./moblie.routes")
const eventRouter = require("./event.routes")
const productRouter = require("./product.routes")
const treeRouter = require("./tree.routes")
const toyRouter = require("./toy.routes")
const jewelleryRouter = require("./jewellery.routes")
const beautyRouter = require("./beauty.routes")
const musicRouter = require("./music.routes")
const bikeRouter = require("./bike.routes")
const clothRouter = require("./cloth.routes")
const electronicRouter = require("./electronic.routes")

const router = express.Router()

router.use("/admin",adminRouter)
router.use("/user",userRouter)
router.use("/book",bookRouter)
router.use("/cartoon",cartoonRouter)
router.use("/movie",movieRouter)
router.use("/subject",subjectRouter)
router.use("/result",resultRouter)
router.use("/blog",blogRouter)
router.use("/river",riverRouter)
router.use("/moblie",moblieRouter)
router.use("/event",eventRouter)
router.use("/product",productRouter)
router.use("/tree",treeRouter)
router.use("/toy",toyRouter)
router.use("/jewellery",jewelleryRouter)
router.use("/beauty",beautyRouter)
router.use("/music",musicRouter)
router.use("/bike",bikeRouter)
router.use("/cloth",clothRouter)
router.use("/electronic",electronicRouter)

module.exports = router